accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('indexs/',views.indexs,name='indexs'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('update/', views.update, name='update'),
    path('<int:account_pk>/profile/',views.profile,name='profile'),
    path('<int:account_pk>/follow/',views.follow,name='follow'),
    path('password/', views.password_change, name='password_change'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    # path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('',include('movies.urls')),
    path('accounts/',include('accounts.urls')),
]

final-projectnew/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('',views.main,name='main'),
    path('index/',views.index,name='index'),
    path('<int:movie_id>/',views.detail,name='detail'),
    path('<int:movie_id>/create/',views.review_create,name='review_create'),
    path('<int:movie_id>/create/<int:review_id>/delete/',views.review_delete,name='review_delete'),
    path('<int:movie_id>/like/',views.like,name='like'),
    path('<int:movie_id>/stars/',views.star,name='stars'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('',views.main,name='main'),
    path('index/',views.index,name='index'),
    path('<int:movie_id>/',views.detail,name='detail'),
    path('<int:movie_id>/create/',views.review_create,name='review_create'),
    path('<int:movie_id>/create/<int:review_id>/delete/',views.review_delete,name='review_delete'),
    path('<int:movie_id>/like/',views.like,name='like'),
    path('<int:movie_id>/stars/',views.star,name='stars'),
]

final-projectnew/movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.TextField()

class Movie(models.Model):
    title = models.TextField()
    audience = models.IntegerField()
    poster_url = models.URLField()
    description = models.TextField()
    genre_id = models.ForeignKey(Genre, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='like_movies')
    original_title = models.TextField()
    css = models.TextField()
    trailer = models.URLField()
    token = models.TextField()
  
class Review(models.Model):
    content = models.TextField()
    score = models.IntegerField()
    movie_id = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.TextField()

class Movie(models.Model):
    title = models.TextField()
    audience = models.IntegerField()
    poster_url = models.URLField()
    description = models.TextField()
    genre_id = models.ForeignKey(Genre, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='like_movies')
    original_title = models.TextField()
    css = models.TextField()
    trailer = models.URLField()
    token = models.TextField()
  
class Review(models.Model):
    content = models.TextField()
    score = models.IntegerField()
    movie_id = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

final-projectnew/movies/forms.py
from .models import Movie,Genre,Review
from django import forms

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user_id','movie_id')

movies/forms.py
from .models import Movie,Genre,Review
from django import forms

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user_id','movie_id')

final-projectnew/movies/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import get_user_model
from .forms import MovieForm,ReviewForm
from .models import Movie,Review, Genre
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseForbidden, JsonResponse, HttpResponse
from IPython import embed
def main(request):
    return render(request,'movies/main.html')
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    genres = Genre.objects.all()
    for movie in movies:
        cnt  = movie.audience
        title = movie.title
    context = {
        'movies':movies,
    }
    k = [0, 1, 2, 3, 4, 5, 7, 9, 11, 15]
    # for i, v in enumerate(genres):
    #     context.update({'genre'+str(i) : v})
    for kk in k:
        m = movies.filter(genre_id=Genre.objects.get(pk=kk))
        if len(m) > 20:
            m = m[0:20]
        context.update({'movie'+str(kk) : m})
    return render(request,'movies/index.html',context)
def detail(request,movie_id):
    movie = get_object_or_404(Movie,id=movie_id)
    reviews = Review.objects.filter(movie_id=movie.pk).order_by('-id')
    if request.user.is_authenticated:
        try:
          movie_review_user = Review.objects.filter(movie_id=movie).filter(user_id=request.user)[0].user_id
        except:
          movie_review_user = -1
    else:
        movie_review_user = -1
    # embed()
    # reviews = reversed(reviews)
    review_form = ReviewForm()
    context = {
        # 'reviews':reviews,
        'movie':movie,
        'review_form':review_form,
        'movie_review_user': movie_review_user
    }
    paginator = Paginator(reviews, 5)
    page = request.GET.get('page')
    try:
      reviews = paginator.page(page)
    except PageNotAnInteger:
      reviews = paginator.page(1)
    except EmptyPage:
      reviews = paginator.page(paginator.num_pages)
    context.update({'reviews': reviews})
    return render(request,'movies/detail.html',context)
@login_required
def review_create(request,movie_id):
    movie = get_object_or_404(Movie,id=movie_id)
    # if request.user.is_authenticated:
    #     return redirect('accounts:login')
    # embed()
    if request.method == 'POST':
        movie_review_user = Review.objects.filter(movie_id=movie).filter(user_id=request.user)
        # embed()
        if movie_review_user:
            review = movie_review_user[0]
        else:
            review = Review()
        try:
            score = int(request.POST['star-input'][0])
        except:
            score = 0
        try:
            content = request.POST['content']
        except:
            content = ''
        # embed()
        review.content = content
        review.score = score
        review.movie_id = movie
        review.user_id = request.user
        review.save()
    return redirect('movies:detail', movie_id)
def review_delete(request,movie_id,review_id):
    review = Review.objects.get(id=review_id)
    review.delete()
    return redirect('movies:detail',movie_id)
@login_required
def like(request,movie_id):
    # 좋아요를 눌렀다면
    # embed()
    if request.is_ajax():
        movie = Movie.objects.get(pk=movie_id)
        if request.user in movie.like_users.all():
            # 좋아요 취소 로직
            movie.like_users.remove(request.user)
            is_liked = False
        # 아니면
        else:
            # 좋아요 로직
            movie.like_users.add(request.user)
            is_liked = True
        context = {
            'is_liked': is_liked,
            'like_count': movie.like_users.count()
            }
        return JsonResponse(context)
    else:
        return HttpResponseForbidden()
    # movie = get_object_or_404(Movie,pk=movie_id)
    # if request.user in movie.like_users.all():
    #     movie.like_users.remove(request.user)
    # else:
    #     movie.like_users.add(request.user)
    # return redirect('movies:detail',movie_id)
@login_required
def star(request, movie_id):
    movie = get_object_or_404(Movie,pk=movie_id)
    score = int(eval(request.body.decode("utf-8"))['score'])
    # embed()

movies/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import get_user_model
from .forms import MovieForm,ReviewForm
from .models import Movie,Review, Genre
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseForbidden, JsonResponse, HttpResponse
from IPython import embed
def main(request):
    return render(request,'movies/main.html')
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    genres = Genre.objects.all()
    for movie in movies:
        cnt  = movie.audience
        title = movie.title
    context = {
        'movies':movies,
    }
    k = [0, 1, 2, 3, 4, 5, 7, 9, 11, 15]
    # for i, v in enumerate(genres):
    #     context.update({'genre'+str(i) : v})
    for kk in k:
        m = movies.filter(genre_id=Genre.objects.get(pk=kk))
        if len(m) > 20:
            m = m[0:20]
        context.update({'movie'+str(kk) : m})
    return render(request,'movies/index.html',context)
def detail(request,movie_id):
    movie = get_object_or_404(Movie,id=movie_id)
    reviews = Review.objects.filter(movie_id=movie.pk).order_by('-id')
    if request.user.is_authenticated:
        try:
          movie_review_user = Review.objects.filter(movie_id=movie).filter(user_id=request.user)[0].user_id
        except:
          movie_review_user = -1
    else:
        movie_review_user = -1
    # embed()
    # reviews = reversed(reviews)
    review_form = ReviewForm()
    context = {
        # 'reviews':reviews,
        'movie':movie,
        'review_form':review_form,
        'movie_review_user': movie_review_user
    }
    paginator = Paginator(reviews, 5)
    page = request.GET.get('page')
    try:
      reviews = paginator.page(page)
    except PageNotAnInteger:
      reviews = paginator.page(1)
    except EmptyPage:
      reviews = paginator.page(paginator.num_pages)
    context.update({'reviews': reviews})
    return render(request,'movies/detail.html',context)
@login_required
def review_create(request,movie_id):
    movie = get_object_or_404(Movie,id=movie_id)
    # if request.user.is_authenticated:
    #     return redirect('accounts:login')
    # embed()
    if request.method == 'POST':
        movie_review_user = Review.objects.filter(movie_id=movie).filter(user_id=request.user)
        # embed()
        if movie_review_user:
            review = movie_review_user[0]
        else:
            review = Review()
        try:
            score = int(request.POST['star-input'][0])
        except:
            score = 0
        try:
            content = request.POST['content']
        except:
            content = ''
        # embed()
        review.content = content
        review.score = score
        review.movie_id = movie
        review.user_id = request.user
        review.save()
    return redirect('movies:detail', movie_id)
def review_delete(request,movie_id,review_id):
    review = Review.objects.get(id=review_id)
    review.delete()
    return redirect('movies:detail',movie_id)
@login_required
def like(request,movie_id):
    # 좋아요를 눌렀다면
    # embed()
    if request.is_ajax():
        movie = Movie.objects.get(pk=movie_id)
        if request.user in movie.like_users.all():
            # 좋아요 취소 로직
            movie.like_users.remove(request.user)
            is_liked = False
        # 아니면
        else:
            # 좋아요 로직
            movie.like_users.add(request.user)
            is_liked = True
        context = {
            'is_liked': is_liked,
            'like_count': movie.like_users.count()
            }
        return JsonResponse(context)
    else:
        return HttpResponseForbidden()
    # movie = get_object_or_404(Movie,pk=movie_id)
    # if request.user in movie.like_users.all():
    #     movie.like_users.remove(request.user)
    # else:
    #     movie.like_users.add(request.user)
    # return redirect('movies:detail',movie_id)
@login_required
def star(request, movie_id):
    movie = get_object_or_404(Movie,pk=movie_id)
    score = int(eval(request.body.decode("utf-8"))['score'])
    # embed()

movies/templates/movies/detail.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'css/jquery.mb.YTPlayer.css' %}" media="all" rel="stylesheet" type="text/css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script src="{% static 'js/jquery.mb.YTPlayer.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static 'css/star.css'%}">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://kit.fontawesome.com/54e342cbc4.js" crossorigin="anonymous"></script>



    <link rel="stylesheet" href="{% static 'css/html5reset-1.6.1.css' %}" type="text/css" media="screen,print">
    <link rel="stylesheet" rel="stylesheet" href="{% static 'css/novacancy.css' %}" type="text/css">
    <script type="text/javascript" src="{% static 'js/jquery.novacancy.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#no').novacancy({
                'reblinkProbability': 0.1,
                'blinkMin': 0.2,
                'blinkMax': 0.6,
                'loopMin': 8,
                'loopMax': 10,
                'color': '#ffffff',
                'glow': ['0 0 80px #ffffff', '0 0 30px #008000', '0 0 6px #0000ff']
            });

            $('#vacancy').novacancy({
                'blink': 1,
                'off': 1,
                'color': 'white',
                'glow': ['0 0 80px Red', '0 0 30px FireBrick', '0 0 6px DarkRed']
            });
            $('#vacancy1').novacancy({
                'blink': 1,
                'off': 1,
                'color': 'black',
                'glow': ['0 0 80px white', '0 0 30px FireBrick', '0 0 6px DarkWhite']
            });
            $('#score').novacancy({
                'blink': 1,
                'off': 1,
                'color': 'white',
                'glow': ['0 0 80px white', '0 0 30px FireBrick', '0 0 6px DarkWhite']
            });
        });
    </script>
    <style>
        
        #vacancy {
            font-family: SCDream6;
            font-size: 40px;
            text-shadow: 0 15px 25px rgb(0, 0, 0);
            font-size: 60px;

        }
        
        .btn {
            top: 70%;
            left: 45%;
            position: absoulte;
            height: 100px;
            width: 200px;
            font-size: 50px;
        }
        .container {
            position: absolute;
            top: 30px;
            left: 20%;
            padding: 4px;
            border: 1px solid #FFFFFF;
            background: rgba(0, 0, 0, 0.7);
            overflow: auto;
            width: 2000px;
            height: 800px;
            margin: 0 auto;
            text-align: center;
        }
        
        @font-face {
            font-size: 100px;
            color: white;
            font-family: SCDream6;
            src: url("{% static 'fonts/SCDream6.otf' %}") format('truetype');
        }
        
        p {
            font-size: 90px;
            color: white;
            font-family: SCDream6;
            text-shadow: 0 5px 15px rgb(0, 0, 0);
        }
        
        h1 {
            font-size: 15px;
            color: rgb(255, 253, 231);
            font-family: SCDream6;
            text-shadow: 0 5px 15px rgb(0, 0, 0);
        }
        
        h2 {
            font-size: 10px;
            color: rgb(255, 253, 231);
            font-family: SCDream6;
            text-shadow: 0 5px 15px rgb(0, 0, 0);
        }
        
        a {
            font-size: 20px;
            color: rgb(27, 27, 27);
            font-family: SCDream6;
            text-shadow: 0 5px 15px rgb(0, 0, 0);
        }
        
        .like,
        .likes {
            font-size: 15px;
            color: rgb(255, 66, 66);
            font-family: SCDream6;
            text-shadow: 0 5px 15px rgb(0, 0, 0);
        }
        
        .nav-link {
            font-size: 20px;
            color: #ffffff;
            font-family: SCDream6;
            text-shadow: 0 5px 15px rgb(0, 0, 0);
        }
        
        span {
            font-size: 20px;
            color: rgb(248, 248, 248);
            font-family: SCDream6;
            text-align: center;
            text-shadow: 0 5px 15px rgb(0, 0, 0);
        }
        
        .num {
            font-size: 20px;
            color: rgb(255, 247, 139);
            font-family: SCDream6;
            text-align: center;
            text-shadow: 0 5px 15px rgb(0, 0, 0);
        }
        
        b {
            color: white;
        }
        
        hr {
            height: 5%;
            opacity: 0;
        }
        
        .alert {
            top: 10px;
            width: 120px;
            height: 40px;
        }
        
        
        #vacancy1 {
            font-size: 15px;
        }
        
        input {
            color: white;
            font-size: 20px;
        }
        
        #delete {
            font-size: 13px;
            width: 70px;
            height: 25px;
        }
        
        .review {
            font-size: 15px;
        }
        
        .reviewbox {
            position: absolute;
            left: 6%;
            bottom: 5%;
            padding: 4px;
            border: 1px solid #FFFFFF;
            background: rgba(10, 10, 10, 0.7);
            overflow: auto;
            width: 1000px;
            height: 250px;
            margin: 0 auto;
            text-align: center;
        }
    </style>

</head>

<body>
    <ul class="nav justify-content-end fixed-top">
        <li class="nav-item">
            <a class="nav-link " href="{% url 'movies:index' %}">HOME</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:profile' user.pk %}">{{ user.username }} </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">SIGNUP</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">LOGIN</a>
        </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:indexs' %}">PROFILE</a>
        </li>
        <div id="bgndVideo" class="player" data-property="{videoURL:'{{movie.trailer}}',containment:'body',autoPlay:true, mute:true, startAt:0, opacity:0.8}">
        </div>
        <div class='container'>
            <hr>
            <p id='vacancy'>{{movie.title}}</p>
            <p id='vacancy1' class="alert alert-light mx-auto" role="alert">{{movie.genre_id.name}}</p>
            <h2 class='num'>{{movie.audience}}만명</h2>
            <h2 class='likes' id="like-count">{{movie.like_users.count}}명이 좋아합니다.</h2>
            {% if user in likemovie.like_users.all%}
            <i id="like-button" data-id="{{movie.id}}" data-user="{{user}}" class="fas fa-heart fa-2x" style="color: red; cursor: pointer;"></i> {% else %}
            <i id="like-button" data-id="{{movie.id}}" data-user="{{user}}" class="far fa-heart fa-2x" style="color: red; cursor: pointer;"></i> {% endif %}

            <hr>
            <h1>{{movie.description}}</h1>

            <div class="reviewbox">
                <br> {% for review in reviews %}
                <p class="review">{{review.user_id.username}}: {{review.content}}
                    <span id="score" style="font-size:15px; color:yellow;"> {{ review.score }}점</span>
                    <a id="delete" class="btn btn-outline-secondary" href="{% url 'movies:review_delete' movie.id review.id %}" role="button">delete</a>
                </p>
                <br /> {% endfor %}
                <div class="pagination">
                    <span class="step-links">
          {% if reviews.has_previous %}
          <a href="?page={{ reviews.previous_page_number }}">previous</a>
          {% endif %}
          <span class="current">
            Page {{ reviews.number }} of {{ reviews.paginator.num_pages }}.
          </span> {% if reviews.has_next %}
                    <a href="?page={{ reviews.next_page_number }}">next</a> {% endif %}
                    </span>
                </div>
                <div>
                    <span class="star-input">
          <form action="{% url 'movies:review_create' movie.pk%}" class="ss" method='POST'>
            {% csrf_token %}
            <span class="input">
              <input type="radio" name="star-input" id="p1" value="1"><label for="p1">1</label>
              <input type="radio" name="star-input" id="p2" value="2"><label for="p2">2</label>
              <input type="radio" name="star-input" id="p3" value="3"><label for="p3">3</label>
              <input type="radio" name="star-input" id="p4" value="4"><label for="p4">4</label>
              <input type="radio" name="star-input" id="p5" value="5"><label for="p5">5</label>
              <input type="radio" name="star-input" id="p6" value="6"><label for="p6">6</label>
              <input type="radio" name="star-input" id="p7" value="7"><label for="p7">7</label>
              <input type="radio" name="star-input" id="p8" value="8"><label for="p8">8</label>
              <input type="radio" name="star-input" id="p9" value="9"><label for="p9">9</label>
              <input type="radio" name="star-input" id="p10" value="10"><label for="p10">10</label>
            </span>
                    <output for="star-input"><b>0</b>점</output>
                    <br>
                    <textarea name="content" id="content" cols="30" rows="1"></textarea> {% if user == movie_review_user %}
                    <input type="submit" value="수정" style="background-color:transparent;"> {% else %}
                    <input type="submit" value="입력" style="color:white; background-color:transparent;"> {% endif %}
                    </form>
                    <br>
                    </span>
                </div>


            </div>


        </div>
</body>
<script>
    $(function() {
        jQuery("#bgndVideo").YTPlayer();
    });
</script>
<script>
    // star rating
    var starRating = function() {
        var $star = $(".star-input"),
            $result = $star.find("output>b");
        console.log($result)
        $(document)
            .on("focusin", ".star-input>form>.input", function() {
                console.log(this)
                $(this).addClass("focus");
            })
            .on("focusout", ".star-input>form>.input", function() {
                var $this = $(this);
                setTimeout(function() {
                    if ($this.find(":focus").length === 0) {
                        $this.removeClass("focus");
                    }
                }, 100);
            })
            .on("change", ".star-input :radio", function() {
                $result.text($(this).next().text());
            })
            .on("mouseover", ".star-input label", function() {
                $result.text($(this).text());
            })
            .on("mouseleave", ".star-input>form>.input", function() {
                var $checked = $star.find(":checked");
                if ($checked.length === 0) {
                    $result.text("0");
                } else {
                    $result.text($checked.next().text());
                }
            });
    };
    starRating();
</script>
<script>
    $(function() {
        jQuery("#bgndVideo").YTPlayer();
    });
</script>
<script>
    const likeButton = document.querySelector('#like-button')
    likeButton.addEventListener('click', function(event) {
        console.log('hi')
        console.log(event.target.dataset.user)
        if (event.target.dataset.user === "AnonymousUser") {
            window.location.href = "/accounts/login/"
        } else {
            console.log('hi')
            axios.defaults.xsrfCookieName = 'csrftoken'
            axios.defaults.xsrfHeaderName = 'X-CSRFToken'
            axios.defaults.headers.common['X-REQUESTED-WITH'] = 'XMLHttpRequest'
            axios.post(`/${event.target.dataset.id}/like/`)
                .then(response => {
                    const likeCount = document.querySelector('#like-count')
                    console.log(response.data.is_liked)
                    if (response.data.is_liked) {
                        event.target.classList.remove('far')
                        event.target.classList.add('fas')
                        console.log(`${response.data.like_count}`)
                        likeCount.innerText = `${response.data.like_count}명이 좋아합니다.`
                    } else {
                        event.target.classList.remove('fas')
                        event.target.classList.add('far')
                        likeCount.innerText = `${response.data.like_count}명이 좋아합니다.`
                    }
                })
                .catch(error => {
                    console.log(error)
                })
        }
    })
</script>

</html>

movies/templates/movies/logbase.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
{% load bootstrap4 %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'css/jquery.mb.YTPlayer.css' %}" media="all" rel="stylesheet" type="text/css">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
    <script src="{% static 'js/jquery.mb.YTPlayer.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static 'css/star.css'%}">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
</head>
<style>

    @font-face {
        font-size: 100px;
        color: white;
        font-family: SCDream6;
        src: url("{% static 'fonts/SCDream6.otf' %}") format('truetype');
    }
    
    p {
        font-size: 50px;
        color: white;
        font-family: SCDream6;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
    }
    
    h1,
    h2 {
        font-size: 13px;
        color: rgb(255, 253, 231);
        font-family: SCDream6;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
    }
    
    a {
        font-size: 20px;
        color: rgb(27, 27, 27);
        font-family: SCDream6;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
    }
    
    .like,
    .likes {
        font-size: 20px;
        color: rgb(255, 66, 66);
        font-family: SCDream6;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
    }
    
    .nav-item {
        font-size: 40px;
        color: rgb(248, 248, 248);
        font-family: SCDream6;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
    }
    
    span {
        font-size: 20px;
        color: rgb(248, 248, 248);
        font-family: SCDream6;
        text-align: center;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
    }
    
    .num {
        font-size: 20px;
        color: rgb(255, 247, 139);
        font-family: SCDream6;
        text-align: center;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
    }
    

    @font-face {
        font-size: 100px;
        color: white;
        font-family: SCDream6;
        src: url("{% static 'fonts/SCDream6.otf' %}") format('truetype');
        text-shadow: 0 5px 15px rgb(0, 0, 0);
    }
    
</style>

<body>
    <ul class="nav justify-content-end fixed-top">
        <li class="nav-item">
            <a class="nav-link " href="{% url 'movies:index' %}">HOME</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:profile' user.pk %}">{{ user.username }} </a>
        </li>
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'accounts:logout' %}">LOGOUT</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:profile' user.pk %}">PROFILE</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">SIGNUP</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">LOGIN</a>
        </li>
        {% endif %}
        
        <div id="bgndVideo" class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=zAGVQLHvwOY',containment:'body',autoPlay:true, mute:true, startAt:0, opacity:0.9}"></div>

{% block body %}
{% endblock  %}

</body>

<script>
    $(function() {
        jQuery("#bgndVideo").YTPlayer();
    });
</script>

</html>