accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('indexs/',views.indexs,name='indexs'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('update/', views.update, name='update'),
    path('<int:account_pk>/profile/',views.profile,name='profile'),
    path('<int:account_pk>/follow/',views.follow,name='follow'),
    path('password/', views.password_change, name='password_change'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    # path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('',include('movies.urls')),
    path('accounts/',include('accounts.urls')),
]

final-projectnew/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('indexs/',views.indexs,name='indexs'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('update/', views.update, name='update'),
    path('<int:account_pk>/profile/',views.profile,name='profile'),
    path('<int:account_pk>/follow/',views.follow,name='follow'),
    path('password/', views.password_change, name='password_change'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('',views.main,name='main'),
    path('index/',views.index,name='index'),
    path('<int:movie_id>/',views.detail,name='detail'),
    path('<int:movie_id>/create/',views.review_create,name='review_create'),
    path('<int:movie_id>/create/<int:review_id>/delete/',views.review_delete,name='review_delete'),
    path('<int:movie_id>/like/',views.like,name='like'),
    path('<int:movie_id>/stars/',views.star,name='stars'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings',blank=True)

final-projectnew/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings',blank=True)

accounts/forms.py
from django.db import models
from .models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username','email','first_name','last_name')
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model() # User return
        fields = ('username', 'first_name', 'last_name')

final-projectnew/accounts/forms.py
from django.db import models
from .models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username','email','first_name','last_name')
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model() # User return
        fields = ('username', 'first_name', 'last_name')

accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import CustomUserCreationForm,CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from .models import User
from movies.models import Review, Movie, Genre
from django.contrib.auth.decorators import login_required




def indexs(request):
    Users = User.objects.all()
    context = {
        'Users':Users
    }
    return render(request,'accounts/indexs.html',context)

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form
    }
    return render(request,'accounts/signup.html',context)
    
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request,user)
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form':form
    }
    return render(request,'accounts/login.html',context)

def logout(request):
    auth_logout(request)
    return redirect('movies:index')

def profile(request, account_pk):
    User = get_user_model()
    user = get_object_or_404(User,pk=account_pk)
    context = {
        'user_profile':user
    }
    genres_score = [0] * 21
    counts = [0] * 21
    reviews = user.review_set.order_by('-score')
    for review in reviews:
      genres_score[review.movie_id.genre_id.id] += review.score
      counts[review.movie_id.genre_id.id] += 1
    ## 장르별 평균점수 계산
    avg_genre = [0] * 21
    for i in range(len(avg_genre)):
      if counts[i] == 0:
        continue
      avg_genre[i] = int(genres_score[i]/counts[i])
    genre = avg_genre.index(max(avg_genre))  # 장르별 점수 최고점
    movies = Movie.objects.filter(genre_id_id=genre).order_by('-audience')
    user_watch_movie = set()
    for r in user.review_set.all():
      user_watch_movie.add(r.movie_id)
    my_movies = []
    if not user_watch_movie:
      genres = Genre.objects.all()
      my_movies = genres[0].movie_set.all()
    else:
      for movie in movies:
        if movie in user_watch_movie:
          continue
        my_movies.append(movie)
        if len(my_movies) == 10:
          break
    context.update({'my_movies': my_movies})
    return render(request,'accounts/profile.html',context)

def follow(request, account_pk):
    User = get_user_model()
    obama = get_object_or_404(User,pk=account_pk)
    if obama != request.user:
        if request.user in obama.followers.all():
            obama.followers.remove(request.user)
        else:
            obama.followers.add(request.user)
        return redirect('accounts:profile',account_pk)

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)


@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user) # 반드시 첫번째 인자로 user
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

final-projectnew/accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import CustomUserCreationForm,CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from .models import User
from movies.models import Review, Movie, Genre
from django.contrib.auth.decorators import login_required




def indexs(request):
    Users = User.objects.all()
    context = {
        'Users':Users
    }
    return render(request,'accounts/indexs.html',context)

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form
    }
    return render(request,'accounts/signup.html',context)
    
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request,user)
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form':form
    }
    return render(request,'accounts/login.html',context)

def logout(request):
    auth_logout(request)
    return redirect('movies:index')

def profile(request, account_pk):
    User = get_user_model()
    user = get_object_or_404(User,pk=account_pk)
    context = {
        'user_profile':user
    }
    genres_score = [0] * 21
    counts = [0] * 21
    reviews = user.review_set.order_by('-score')
    for review in reviews:
      genres_score[review.movie_id.genre_id.id] += review.score
      counts[review.movie_id.genre_id.id] += 1
    ## 장르별 평균점수 계산
    avg_genre = [0] * 21
    for i in range(len(avg_genre)):
      if counts[i] == 0:
        continue
      avg_genre[i] = int(genres_score[i]/counts[i])
    genre = avg_genre.index(max(avg_genre))  # 장르별 점수 최고점
    movies = Movie.objects.filter(genre_id_id=genre).order_by('-audience')
    user_watch_movie = set()
    for r in user.review_set.all():
      user_watch_movie.add(r.movie_id)
    my_movies = []
    if not user_watch_movie:
      genres = Genre.objects.all()
      my_movies = genres[0].movie_set.all()
    else:
      for movie in movies:
        if movie in user_watch_movie:
          continue
        my_movies.append(movie)
        if len(my_movies) == 10:
          break
    context.update({'my_movies': my_movies})
    return render(request,'accounts/profile.html',context)

def follow(request, account_pk):
    User = get_user_model()
    obama = get_object_or_404(User,pk=account_pk)
    if obama != request.user:
        if request.user in obama.followers.all():
            obama.followers.remove(request.user)
        else:
            obama.followers.add(request.user)
        return redirect('accounts:profile',account_pk)

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)


@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user) # 반드시 첫번째 인자로 user
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

accounts/templates/accounts/indexs.html
{% extends 'movies/base.html' %}
{% block body %}

<a href="{% url 'movies:index'%}">돌아가기</a>
{% for user in Users %}
<br>
<h1>
<a href="{% url 'accounts:profile' user.pk %}">{{user.username}}</a>
</h1>

{% endfor %}

{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'movies/logbase.html' %}
{% load bootstrap4 %}
{% block body %}
{% load static %}

<form class="mx-auto my-auto" action="" method='POST'>
<h1>LOGIN</h1>
{% csrf_token %}
{% bootstrap_form form %}
<input type="submit">
</form> 
<style>
    h1 {
        position: absolute;
        top:150px;
        left: 42%;
        font-size: 100px;
        color: rgb(248, 248, 248);
        font-family: SCDream6;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
        text-align: center;
    }
    form {
        font-family: SCDream6;
        position: absolute;
        top: 100px;
        left: 3%;
        padding: 400px 600px 20px 600px;
        background: rgba( 0, 0, 0, 0.7);
        overflow: auto;
        margin: 0 auto;
        text-align: center;
        width: 1800px;
        height:800px;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
        color:white;
    }
</style> 
{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'movies/logbase.html' %}
{% block body %}
{% load bootstrap4%}

<form action="">

    <div class="container">
    <h1>{{user_profile.username}}의 프로필</h1>
    <hr>
        <div class="row">
            <div class="row-md-3">
            <h3>프로필</h3>
                <a class="log" href="{% url 'accounts:update' %}">회원정보수정</a>
                <a class="log" href="{% url 'accounts:password_change' %}">비밀번호수정</a>  
            </div>
            <div class="row-md-3">
            <h3>팔로우 하기</h3>
                         

                <h2>팔로우 : {{user_profile.followings.all.count}}</h2>
                <h2>팔로워 : {{user_profile.followers.all.count}}</h2>

                <a href="{% url 'accounts:follow' user_profile.pk %}">
                {% if user_profile.user != require.user %}
                    {% if user in user_profile.followers.all %}
                    <p>팔로우 취소</p>
                    {% else %}
                    <p>팔로우</p>
                    {% endif %}
                {% endif %}
                </a>
            </div>
            <div class="row-md-3">
            <h3>추천 영화</h3>
            {% for movie in my_movies %}
                <div class="container">
                <a href="{% url 'movies:detail' movie.pk %}">#{{movie.title}}
                </div>
            {% endfor %}
            </div>
            <div class="row-md-3">
                <h3>내가 좋아요 한 영화</h3>
                {% for movie in user_profile.like_movies.all %}
                <p><a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</p>
                <img src="{{movie.poster_url}}" alt="">
                {% endfor %}

            </div>
        </div>         
    </div>
</form>


<style>
hr {
    height:3px;
    background-color: #ffffff;
}
    .row{
        position: absolute;
        left: 10%;
    }
    .row-md-3 {
        margin:20px 50px 20px 50px;
    }
    .container {
        margin:0 auto;
    }
    img {
        width: 100px;
    }

    a {
        font-size:15px;
        color: white;
    }

    .log {
        bottom: 50px;
        right: 50px;
        font-size: 15px;
        color: rgb(248, 248, 248);
        font-family: SCDream6;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
    }

    h3 {
        font-size: 30px;
        color: rgb(200, 66, 66);
        font-family: SCDream6;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
    }

    h2 {
        font-size: 30px;
        color: rgb(248, 248, 248);
        font-family: SCDream6;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
    }

    h1 {
        top: 50px;
        font-size: 70px;
        color: rgb(248, 248, 248);
        font-family: SCDream6;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
    }

    form {
        font-family: SCDream6;
        position: absolute;
        top: 100px;
        left: 3%;
        padding: 50px 10px 20px 10px;
        background: rgba(0, 0, 0, 0.7);
        overflow: auto;
        width: 1800px;
        height: 800px;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
        color: white;
        text-align: center;
    }
</style>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'movies/logbase.html' %}
{% load bootstrap4 %}
{% block body %}

<form class="mx-auto ml-auto" action="" method='POST'>
<h1>SIGNUP</h1>
{% csrf_token %}
{% bootstrap_form form %}
<input type="submit">
</form>
<style>
    h1 {
        position: absolute;
        top:20px;
        left: 40%;
        font-size: 100px;
        color: rgb(248, 248, 248);
        font-family: SCDream6;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
        text-align: center;
    }
    form {
        font-family: SCDream6;
        position: absolute;
        top: 50px;
        left: 3%;
        padding: 150px 600px 20px 600px;
        background: rgba( 0, 0, 0, 0.7);
        overflow: auto;
        margin: 0 auto;
        text-align: center;
        width: 1800px;
        height:850px;
        text-shadow: 0 5px 15px rgb(0, 0, 0);
        color:white;
    }
</style>

{% endblock  %}